# 22(최신), 기본 이미지 선택
FROM ubuntu:18.04
# 리눅스 설치 : 유틸리티 프로그램 설치
# iputils-ping net-tools git vim : apt-get
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install iputils-ping -y
RUN apt-get install net-tools -y
RUN apt-get install git -y
RUN apt-get install vim -y